/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Socio;
/**
 *
 * @author Cristóbal Varas
 */
public class PagarCuota extends javax.swing.JFrame {

    /**
     * Creates new form PagarCuota
     */
    private ArrayList<Socio> socios;
    
    public PagarCuota() {
        initComponents();
        cargarDatosSocios(); // Cargar datos simulados
    }
    
     private void cargarDatosSocios() {
        socios = new ArrayList<>();

        // Crear datos de ejemplo
        Socio socio1 = new Socio("12345678-9", "Juan", "Perez", "Yoma", "987654321", "Avenida Siempre Viva", "Santiago", 1111);
        socio1.agregarCuota(new Cuota(1, 5000, false));
        socio1.agregarCuota(new Cuota(2, 5000, false));

        Socio socio2 = new Socio("25123456-7", "Maria", "Yoma", "Perez", "123456789", "Avenida A Veces Viva", "Santiago", 1112);
        socio2.agregarCuota(new Cuota(1, 7000, true)); // Cuota ya pagada
        socio2.agregarCuota(new Cuota(2, 7000, false));

        // Agregar a la lista
        socios.add(socio1);
        socios.add(socio2);
    }
     
     
     private Socio buscarSocioPorRut(String rut) {
        for (Socio socio : socios) {
            if (socio.getRut().equalsIgnoreCase(rut)) {
                return socio;
            }
        }
        return null;
    }

     
     private void pagarCuota(Socio socio, int numeroCuota) {
        Cuota cuota = socio.buscarCuota(numeroCuota);
        if (cuota == null) {
            JOptionPane.showMessageDialog(this, "La cuota no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cuota.isPagada()) {
            JOptionPane.showMessageDialog(this, "La cuota ya está pagada.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        cuota.setPagada(true); // Marcar como pagada
        JOptionPane.showMessageDialog(this, "Cuota pagada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRutSocio = new javax.swing.JLabel();
        tfdRutSocio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblMontoCuota = new javax.swing.JLabel();
        tfdMontoCuota = new javax.swing.JTextField();
        lblNumeroCuota = new javax.swing.JLabel();
        tfdNumeroCuota = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRutSocio.setText("Rut Socio");

        tfdRutSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdRutSocioActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblMontoCuota.setText("Monto Cuota");

        lblNumeroCuota.setText("Número Cuota");

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscar)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRutSocio)
                                        .addComponent(tfdRutSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroCuota)
                                    .addComponent(lblMontoCuota))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdNumeroCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnPagar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblRutSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdRutSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoCuota)
                    .addComponent(tfdMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCuota)
                    .addComponent(tfdNumeroCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnPagar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdRutSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdRutSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdRutSocioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String rut = tfdRutSocio.getText().trim();
        Socio socio = buscarSocioPorRut(rut);

        if (socio == null) {
            JOptionPane.showMessageDialog(this, "Socio no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Socio encontrado: " + socio.getNombre(), "Éxito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String rut = tfdRutSocio.getText().trim();
        Socio socio = buscarSocioPorRut(rut);

        if (socio == null) {
            JOptionPane.showMessageDialog(this, "Debes buscar un socio válido antes de pagar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int numeroCuota = Integer.parseInt(tfdNumeroCuota.getText().trim());
            pagarCuota(socio, numeroCuota);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de cuota debe ser un valor numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel lblMontoCuota;
    private javax.swing.JLabel lblNumeroCuota;
    private javax.swing.JLabel lblRutSocio;
    private javax.swing.JTextField tfdMontoCuota;
    private javax.swing.JTextField tfdNumeroCuota;
    private javax.swing.JTextField tfdRutSocio;
    // End of variables declaration//GEN-END:variables
}


public class Cuota {
    private int numero;
    private double monto;
    private boolean pagada;

    public Cuota(int numero, double monto, boolean pagada) {
        this.numero = numero;
        this.monto = monto;
        this.pagada = pagada;
    }

    public int getNumero() {
        return numero;
    }

    public double getMonto() {
        return monto;
    }

    public boolean isPagada() {
        return pagada;
    }

    public void setPagada(boolean pagada) {
        this.pagada = pagada;
    }
}