/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.util.ArrayList;
import javax.swing.*;
import model.Socio;
/**
 *
 * @author Cristóbal Varas
 */
public class MainMenu extends javax.swing.JFrame {

    private ArrayList<Socio> listaSocios;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        listaSocios = new ArrayList<>();
        
         listaSocios.add(new Socio("12.345.678-9", "Cristóbal", "Santiago", "Avenida Siempre Viva", "Polanco", "Varas", "123456789", 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmnSocio = new javax.swing.JMenu();
        jmnRegistrarSocio = new javax.swing.JMenuItem();
        jmnVerDatosSocio = new javax.swing.JMenuItem();
        jmnCuentaSocio = new javax.swing.JMenu();
        jmnPagarCuotaMensual = new javax.swing.JMenuItem();
        jmnConsultarMonto = new javax.swing.JMenuItem();
        jmnConsultarNumeroCuotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmnSocio.setText("Socio");
        jmnSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSocioActionPerformed(evt);
            }
        });

        jmnRegistrarSocio.setText("Registrar Socio");
        jmnRegistrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRegistrarSocioActionPerformed(evt);
            }
        });
        jmnSocio.add(jmnRegistrarSocio);

        jmnVerDatosSocio.setText("Ver Datos Socio");
        jmnVerDatosSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnVerDatosSocioActionPerformed(evt);
            }
        });
        jmnSocio.add(jmnVerDatosSocio);

        jMenuBar1.add(jmnSocio);

        jmnCuentaSocio.setText("Cuenta Socio");

        jmnPagarCuotaMensual.setText("Pagar Cuota Mensual");
        jmnPagarCuotaMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnPagarCuotaMensualActionPerformed(evt);
            }
        });
        jmnCuentaSocio.add(jmnPagarCuotaMensual);

        jmnConsultarMonto.setText("Consultar Monto Total Cancelado");
        jmnConsultarMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnConsultarMontoActionPerformed(evt);
            }
        });
        jmnCuentaSocio.add(jmnConsultarMonto);

        jmnConsultarNumeroCuotas.setText("Consultar N° Cuotas por Cancelar");
        jmnConsultarNumeroCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnConsultarNumeroCuotasActionPerformed(evt);
            }
        });
        jmnCuentaSocio.add(jmnConsultarNumeroCuotas);

        jMenuBar1.add(jmnCuentaSocio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnVerDatosSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVerDatosSocioActionPerformed
        // TODO add your handling code here:
        StringBuilder datos = new StringBuilder("Datos de los Socios:\n");
        for (Socio socio : listaSocios) {
            datos.append(socio.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(this, datos.toString(), "Datos Socios", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jmnVerDatosSocioActionPerformed

    private void jmnSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSocioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmnSocioActionPerformed

    private void jmnRegistrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRegistrarSocioActionPerformed
        // TODO add your handling code here:
        RegistrarSocioFrame registrarFrame = new RegistrarSocioFrame();
        registrarFrame.setVisible(true);
    }//GEN-LAST:event_jmnRegistrarSocioActionPerformed

    private void jmnPagarCuotaMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnPagarCuotaMensualActionPerformed
        // TODO add your handling code here:
        if (listaSocios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay socios registrados.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Solicitar RUT
        String rutSocio = JOptionPane.showInputDialog(this, "Ingrese el RUT del socio que desea pagar la cuota:");
        if (rutSocio == null || rutSocio.isEmpty()) {
            return; // Cancelado o vacío
        }
        
        // Buscar socio
        Socio socioSeleccionado = null;
        for (Socio socio : listaSocios) {
            if (socio.getRut().equals(rutSocio)) {
                socioSeleccionado = socio;
                break;
            }
        }

        if (socioSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Socio no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Solicitar monto
        String montoInput = JOptionPane.showInputDialog(this, "Ingrese el monto a pagar:");
        if (montoInput == null || montoInput.isEmpty()) {
            return; // Cancelado o vacío
        }

        try {
            int monto = Integer.parseInt(montoInput);
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Actualizar el monto pagado
            socioSeleccionado.setMontoPagado(socioSeleccionado.getMontoPagado() + monto);

            JOptionPane.showMessageDialog(this, "Pago registrado con éxito.\n" +
                    "Socio: " + socioSeleccionado.getNombre() + "\n" +
                    "Monto Total Pagado: " + socioSeleccionado.getMontoPagado(), 
                    "Pago Realizado", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmnPagarCuotaMensualActionPerformed

    private void jmnConsultarMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnConsultarMontoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad 'Consultar Monto Total Cancelado' no implementada aún.");
    }//GEN-LAST:event_jmnConsultarMontoActionPerformed

    private void jmnConsultarNumeroCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnConsultarNumeroCuotasActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Funcionalidad 'Consultar N° Cuotas por Cancelar' no implementada aún.");
    }//GEN-LAST:event_jmnConsultarNumeroCuotasActionPerformed
                                            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmnConsultarMonto;
    private javax.swing.JMenuItem jmnConsultarNumeroCuotas;
    private javax.swing.JMenu jmnCuentaSocio;
    private javax.swing.JMenuItem jmnPagarCuotaMensual;
    private javax.swing.JMenuItem jmnRegistrarSocio;
    private javax.swing.JMenu jmnSocio;
    private javax.swing.JMenuItem jmnVerDatosSocio;
    // End of variables declaration//GEN-END:variables
}
