/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.Socio;
import javax.swing.*;
import java.util.ArrayList;



/**
 *
 * @author Cristóbal Varas
 */
public class RegistrarSocioFrame extends javax.swing.JFrame {

    // Lista para almacenar los socios registrados
    public static ArrayList<Socio> listaSocios = new ArrayList<>();

    /**
     * Creates new form RegistrarSocioFrame
     */
    public RegistrarSocioFrame() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApaterno = new javax.swing.JLabel();
        lblAmaterno = new javax.swing.JLabel();
        tfdRut = new javax.swing.JTextField();
        tfdApaterno = new javax.swing.JTextField();
        tfdNombre = new javax.swing.JTextField();
        tfdAmaterno = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        tfdTelefono = new javax.swing.JTextField();
        tfdDomicilio = new javax.swing.JTextField();
        tfdComuna = new javax.swing.JTextField();
        lblNroSocio = new javax.swing.JLabel();
        tfdNroSocio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRut.setText("Rut");

        lblNombre.setText("Nombre");

        lblApaterno.setText("Apellido Paterno");

        lblAmaterno.setText("Apellido Materno");

        tfdRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdRutActionPerformed(evt);
            }
        });

        lblTelefono.setText("Telefono");

        lblDomicilio.setText("Domicilio");

        lblComuna.setText("Comuna");

        tfdTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTelefonoActionPerformed(evt);
            }
        });

        lblNroSocio.setText("Numero de Socio");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNroSocio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdNroSocio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRut)
                        .addComponent(tfdRut, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefono)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre)
                    .addComponent(tfdNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(lblDomicilio)
                    .addComponent(tfdDomicilio))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComuna)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfdComuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(lblApaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdApaterno, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmaterno)
                            .addComponent(tfdAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblApaterno)
                            .addGap(4, 4, 4)
                            .addComponent(tfdApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRut)
                                .addComponent(lblNombre))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfdRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmaterno)
                        .addGap(4, 4, 4)
                        .addComponent(tfdAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblDomicilio)
                    .addComponent(lblComuna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblNroSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tfdRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdRutActionPerformed

    private void tfdTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTelefonoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         // TODO add your handling code here:
         registrarSocio(evt);         
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    
    private void registrarSocio(java.awt.event.ActionEvent evt) {                                
        // Lógica para registrar el socio
        try {
            String rut = tfdRut.getText();
            String nombre = tfdNombre.getText();
            String apellidoPaterno = tfdApaterno.getText();
            String apellidoMaterno = tfdAmaterno.getText();
            String telefono = tfdTelefono.getText();
            String domicilio = tfdDomicilio.getText();
            String comuna = tfdComuna.getText();
            int numeroSocio;

            // Validar que el número de socio sea un entero
            try {
                numeroSocio = Integer.parseInt(tfdNroSocio.getText());
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("El número de socio debe ser un número válido.");
            }

            // Validaciones
            if (rut.isEmpty() || nombre.isEmpty() || apellidoPaterno.isEmpty() || telefono.isEmpty()) {
                throw new IllegalArgumentException("Todos los campos obligatorios deben estar llenos.");
            }

            if (rut.length() < 11 || rut.length() > 12) {
                throw new IllegalArgumentException("El RUT debe tener entre 11 y 12 caracteres (incluyendo puntos y guión).");
            }

            // Crear objeto Socio
            Socio nuevoSocio = new Socio(rut, nombre, apellidoPaterno, apellidoMaterno, telefono, domicilio, comuna, numeroSocio);

            // Guardar el socio en la lista
            listaSocios.add(nuevoSocio);

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Socio registrado con éxito:\n" + nuevoSocio);

            // Limpiar los campos
            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                               

    private void limpiarCampos() {
        tfdRut.setText("");
        tfdApaterno.setText("");
        tfdNombre.setText("");
        tfdAmaterno.setText("");
        tfdTelefono.setText("");
        tfdDomicilio.setText("");
        tfdComuna.setText("");
        tfdNroSocio.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarSocioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarSocioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarSocioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarSocioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarSocioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblAmaterno;
    private javax.swing.JLabel lblApaterno;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroSocio;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField tfdAmaterno;
    private javax.swing.JTextField tfdApaterno;
    private javax.swing.JTextField tfdComuna;
    private javax.swing.JTextField tfdDomicilio;
    private javax.swing.JTextField tfdNombre;
    private javax.swing.JTextField tfdNroSocio;
    private javax.swing.JTextField tfdRut;
    private javax.swing.JTextField tfdTelefono;
    // End of variables declaration//GEN-END:variables
}
