/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import model.Socio;
import javax.swing.*;
import java.util.ArrayList;
/**
 *
 * @author Cristóbal Varas
 */
public class VerDatosSocio extends javax.swing.JFrame {

     private ArrayList<Socio> listaSocios;
    /**
     * Creates new form VerDatosSocio
     */
    public VerDatosSocio(ArrayList<Socio> listaSocios) {
        this.listaSocios = listaSocios; // Inicializamos la lista de socios
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAmaterno = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblApaterno = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        tfdIngresoRut = new javax.swing.JTextField();
        tfdNombre = new javax.swing.JTextField();
        tfdComuna = new javax.swing.JTextField();
        tfdDomicilio = new javax.swing.JTextField();
        tfdAmaterno = new javax.swing.JTextField();
        tfdTelefono = new javax.swing.JTextField();
        tfdApaterno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Socio");

        lblIngresoRut.setText("Ingrese Rut de Socio");

        lblNombre.setText("Nombre");

        lblAmaterno.setText("Apellido Materno");

        lblTelefono.setText("Teléfono");

        lblApaterno.setText("Apellido Paterno");

        lblComuna.setText("Comuna");

        lblDomicilio.setText("Domicilio");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tfdNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIngresoRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfdIngresoRut)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmaterno)
                    .addComponent(lblApaterno)
                    .addComponent(lblNombre)
                    .addComponent(tfdNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(tfdApaterno)
                    .addComponent(tfdAmaterno))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDomicilio)
                    .addComponent(lblComuna)
                    .addComponent(lblTelefono)
                    .addComponent(tfdDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(tfdComuna)
                    .addComponent(tfdTelefono))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresoRut)
                    .addComponent(lblNombre)
                    .addComponent(lblDomicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdIngresoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApaterno)
                    .addComponent(lblComuna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmaterno)
                    .addComponent(lblTelefono)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String rutIngresado = tfdIngresoRut.getText().trim();
        
        if (rutIngresado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un RUT válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Eliminar puntos y guión del RUT ingresado
        String rutIngresadoSinFormato = rutIngresado.replaceAll("[^\\d]", "");
        
        for (Socio socio : listaSocios) {
            // Eliminar puntos y guión del RUT del socio
            String rutSocioSinFormato = socio.getRut().replaceAll("[^\\d]", "");

            if (rutSocioSinFormato.equals(rutIngresadoSinFormato)) {
                // Mostrar datos en los campos de texto
                tfdNombre.setText(socio.getNombre());
                tfdComuna.setText(socio.getApellidoPaterno());
                tfdDomicilio.setText(socio.getApellidoMaterno());
                tfdAmaterno.setText(socio.getTelefono());
                tfdTelefono.setText(socio.getComuna());
                tfdApaterno.setText(socio.getDomicilio());
                return;
            }
        }
        
        JOptionPane.showMessageDialog(this, "Socio no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        
        limpiarCampos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void limpiarCampos() {
        tfdNombre.setText(""); // Nombre
        tfdComuna.setText(""); // Apellido Paterno
        tfdDomicilio.setText(""); // Apellido Materno
        tfdAmaterno.setText(""); // Teléfono
        tfdTelefono.setText(""); // Comuna
        tfdApaterno.setText(""); // Domicilio
    }
    private void tfdNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // Crear una lista vacía de socios
    ArrayList<Socio> listaSocios = new ArrayList<>();

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(VerDatosSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Crear y mostrar la ventana con la lista de socios vacía
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new VerDatosSocio(listaSocios).setVisible(true);  // Pasa la lista de socios al constructor
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblAmaterno;
    private javax.swing.JLabel lblApaterno;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblIngresoRut;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField tfdAmaterno;
    private javax.swing.JTextField tfdApaterno;
    private javax.swing.JTextField tfdComuna;
    private javax.swing.JTextField tfdDomicilio;
    private javax.swing.JTextField tfdIngresoRut;
    private javax.swing.JTextField tfdNombre;
    private javax.swing.JTextField tfdTelefono;
    // End of variables declaration//GEN-END:variables
}
